# .scrutinizer.yml

checks:
    python:
        code_rating: true
        duplicate_code: true


tools:
    pylint:
        python_version: 2     # Possible values: 2, 3
        config_file: '.pylintrc'
