# .scrutinizer.yml

checks:
    python:
        code_rating: true
        duplicate_code: true
        variables_unused_variable: true
        variables_unused_wildcard_import: true
        variables_used_before_assignment: true
        variables_unused_import: true
        variables_unused_argument: true
        variables_unpacking_non_sequence: true
        variables_undefined_variable: true
        variables_undefined_loop_variable: true
        variables_undefined_all_variable: true
        variables_unbalanced_tuple_unpacking: true
        variables_redefined_outer_name: true
        variables_redefined_builtin: true
        variables_redefine_in_handler: true
        variables_no_name_in_module: true
        variables_invalid_all_object: true
        variables_global_variable_undefined: true
        variables_global_variable_not_assigned: true
        variables_global_statement: true
        variables_global_at_module_level: true
        typecheck_unexpected_keyword_arg: true
        typecheck_too_many_function_args: true
        typecheck_redundant_keyword_arg: true
        typecheck_not_callable: true
        typecheck_no_value_for_parameter: true
        typecheck_no_member: true
        typecheck_missing_kwoa: true
        typecheck_duplicate_keyword_arg: true
        typecheck_maybe_no_member: true
        typecheck_assignment_from_none: true
        typecheck_assignment_from_no_return: true

        
filter:
    excluded_paths:
        - '*/test/*'
